"use client"
import React, { useEffect, useState } from "react";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "./src/components/Footer/Footer";
import HeaderBar from "./src/components/Home/HeaderBar";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <head>
//         <title>
//           BotLab Dynamics | India&apos;s Leading Drone Show Company
//         </title>

//       </head>
//       <body className={inter.className}>

//         <div className="fixed w-full sm:h-0 inset-0  z-[150]">
//           <HeaderBar />
//         </div> 

//       <main>{children}</main>
//         {/* {
//           footerDelay &&  */}
//         <Footer />
//         {/* } */}
//       </body>
//     </html>
//   );
// }
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* <title>BotLab Dynamics | India's Leading Drone Show Company</title> */}
        {/* Add meta tags and links if necessary */}
      </head>
      <body className={inter.className}>


        <div className="fixed w-full top-0 z-[150]">
          <HeaderBar />
        </div>


        <main className="pt-20">
          {children}
        </main>

        <div className="">
          <Footer />
        </div>
      </body>
    </html>
  );
}